# Generated by Django 5.2.17 on 2026-08-07 06:27

import complaints.models
import complaints.storage
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("content", models.BinaryField()),
                ("size", models.PositiveIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "stored file",
                "verbose_name_plural": "stored files",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AlterField(
            model_name="complaintattachment",
            name="file",
            field=models.FileField(
                storage=complaints.storage.AttachmentStorage(),
                upload_to=complaints.models.attachment_upload_path,
                verbose_name="file",
            ),
        ),
    ]
