# Generated by Django 5.2.17 on 2026-08-06 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("submitted", "Complaint submitted"),
                            ("assigned", "Complaint assigned"),
                            ("status_changed", "Status changed"),
                            ("remark", "Remark added"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="recipient"),
                ),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("SUPPRESSED", "Suppressed"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "complaint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="complaints.complaint",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="notificatio_status_d92267_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="notificatio_created_ae6ed6_idx"
                    ),
                ],
            },
        ),
    ]
